pipeline:
  name: cypress_pipeline_fddd984e38124a798289057fd320155a
  identifier: cypress_pipeline_fddd984e38124a798289057fd320155a
  projectIdentifier: cypress_project_e841e5f68e8341f689f9b17069bf7188
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_d8bff43da7094054b33c446abf31de9a
        identifier: cypress_stage_d8bff43da7094054b33c446abf31de9a
        tags: {}
        template:
          templateRef: cypress_template_532dd160548d4e66845b29d8b125e319
          versionLabel: v1
          gitBranch: main
