pipeline:
  name: cypress_pipeline_adf12b59ca0945009fc69d8bcca938de
  identifier: cypress_pipeline_adf12b59ca0945009fc69d8bcca938de
  projectIdentifier: cypress_project_2f81531ff3c24db980f53ea6eca02c07
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_bf2e1965b4ed4bde9711527e13fdeb87
        identifier: cypress_stage_bf2e1965b4ed4bde9711527e13fdeb87
        tags: {}
        template:
          templateRef: cypress_template_84baffa71a4b4c03aea6fd2758f449cb
          versionLabel: v1
          gitBranch: main
