pipeline:
  name: cypress_pipeline_ec4c3b66dddd43528168d7aa1570fe2a
  identifier: cypress_pipeline_ec4c3b66dddd43528168d7aa1570fe2a
  projectIdentifier: cypress_project_8449b57e2b184ab4afc2239cb814c56e
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_c6b49aa0db394ad9adbafe712cef3d8f
        identifier: cypress_stage_c6b49aa0db394ad9adbafe712cef3d8f
        tags: {}
        template:
          templateRef: cypress_template_904ff5d09d454b2089ac813b436bf6db
          versionLabel: v1
          gitBranch: main
