pipeline:
  name: cypress_pipeline_ab887b32f00c43b5af5e71da57d785db
  identifier: cypress_pipeline_ab887b32f00c43b5af5e71da57d785db
  projectIdentifier: cypress_project_6992a996d4bf44d6bbe76cce765bb0b5
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_02ed4819f9a54091be51c71e2fa169b2
        identifier: cypress_stage_02ed4819f9a54091be51c71e2fa169b2
        tags: {}
        template:
          templateRef: cypress_template_a91d5609392b46bb8824335de3897ef4
          versionLabel: v1
